query getChatRoom($chatRoomId: String!) {
  chatRoom(chatRoomId: $chatRoomId) {
    id
    title
    url
    messages {
      id
      content
      createdAt
      user {
        id
        name
      }
    }
  }
}